### ISSUE TITLE
Label exported articles?

### ISSUE THREAD

**Issue by kevinschaul** [mgaitan/omnivook#7]
This software looks fantastic, @mgaitan!

My dream setup is for a command to create a book with all articles not previously exported, but to not archive the articles in case I want to read them in the Omnivore app. I think this would be possible if I could apply a label to exported articles. I would then exclude that label from future exports.

I tried to build this feature into [a similar project](https://github.com/agrmohit/omnivore-epub/issues/2) but could not figure out the proper GraphQL syntax. Do you know if such a feature is possible?

**Comment by mgaitan** [comment]
@kevinschaul I liked the idea, so I've just implemented it! 

now we have these options  (note it's comma separated)

``` 
  --label LABEL         Comma-separated labels to filter articles (optional)
  --exclude-label EXCLUDE_LABEL
                        Comma-separated labels to exclude articles (optional)
  --add-label ADD_LABEL
                        Comma-separated labels to add to exported articles
````

For example 

```
$ omnivook --mode retrieve --exclude-label "Newsletter, RSS" --add-label "foo, omnivook"
```

**Comment by mgaitan** [comment]
try version 0.1.5!

**Comment by kevinschaul** [comment]
Very nice! Thank you!
